# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tmux"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dominik Honnef", "Abhi Yerra"]
  s.date = "2011-10-02"
  s.description = "Allow Ruby to interact with Tmux"
  s.email = "dominikh@fork-bomb.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".yardopts",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/tmux.rb",
    "lib/tmux/buffer.rb",
    "lib/tmux/client.rb",
    "lib/tmux/exception.rb",
    "lib/tmux/exception/basic_exception.rb",
    "lib/tmux/exception/in_tmux.rb",
    "lib/tmux/exception/index_in_use.rb",
    "lib/tmux/exception/unknown_command.rb",
    "lib/tmux/exception/unsupported_version.rb",
    "lib/tmux/filterable_hash.rb",
    "lib/tmux/options.rb",
    "lib/tmux/options/attr_option.rb",
    "lib/tmux/options/bell_action_option.rb",
    "lib/tmux/options/boolean_option.rb",
    "lib/tmux/options/char_array_option.rb",
    "lib/tmux/options/clock_mode_style_option.rb",
    "lib/tmux/options/color_option.rb",
    "lib/tmux/options/justification_option.rb",
    "lib/tmux/options/keymap_option.rb",
    "lib/tmux/options/number_option.rb",
    "lib/tmux/options/option.rb",
    "lib/tmux/options/string_option.rb",
    "lib/tmux/options/symbol_option.rb",
    "lib/tmux/options/word_array_option.rb",
    "lib/tmux/options_list.rb",
    "lib/tmux/pane.rb",
    "lib/tmux/server.rb",
    "lib/tmux/session.rb",
    "lib/tmux/status_bar.rb",
    "lib/tmux/status_bar/field.rb",
    "lib/tmux/widget.rb",
    "lib/tmux/widgets/progress_bar.rb",
    "lib/tmux/window.rb",
    "lib/tmux/window/status.rb",
    "lib/tmux/window/status/state.rb",
    "screenshots/progress_bar.png",
    "tmux.gemspec"
  ]
  s.homepage = "http://github.com/abhiyerra/tmux"
  s.licenses = ["BSD"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Allow Ruby to interact with Tmux"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<filesize>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<filesize>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<filesize>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

